logging:
  level: INFO
  log_dir: logs
  format: "%(asctime)s [%(levelname)s] %(message)s"

jquants:
  auth:
    email: ${JQ_EMAIL}
    password: ${JQ_PASSWORD}
  endpoints:
    token_auth_user: https://api.jquants.com/v1/token/auth_user
    token_auth_refresh: https://api.jquants.com/v1/token/auth_refresh
    trading_calendar: https://api.jquants.com/v1/markets/trading_calendar
    daily_quotes: https://api.jquants.com/v1/prices/daily_quotes
    listed_info: https://api.jquants.com/v1/listed/info
    futures_prices: https://api.jquants.com/v1/derivatives/futures
    weekly_margin_interest: https://api.jquants.com/v1/markets/weekly_margin_interest
    short_selling_positions: https://api.jquants.com/v1/markets/short_selling_positions
    trades_spec: https://api.jquants.com/v1/markets/trades_spec
  
database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}

BACKTEST_N_JOBS: 16        # Ryzen 9 5950X 推奨値
